// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package storage

//*
// @brief Field data type
type DataType int32

const (
	DataType_None         DataType = 0
	DataType_Bool         DataType = 1
	DataType_Int8         DataType = 2
	DataType_Int16        DataType = 3
	DataType_Int32        DataType = 4
	DataType_Int64        DataType = 5
	DataType_Float        DataType = 10
	DataType_Double       DataType = 11
	DataType_String       DataType = 20
	DataType_BinaryVector DataType = 100
	DataType_FloatVector  DataType = 101
)
